name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@main
      with:
        ref: main
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert pytest pytest-cov
        pip install -e .

    - name: Test with pytest
      run: |
        pip install pytest
        pytest --cov=process_bigraph
